version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r "домашка 10/requirements.txt"
      - run:
          name: Run tests
          command: pytest "домашка 10/tests/" -v

workflows:
  run-tests:
    jobs:
      - test
